# This is a GNU make file that uses GNU make make extensions

top_srcdir := ../..

# There to install selected files in this directory
INSTALL_DIR = $(SERVER_DOC_ROOT)/icons

include $(top_srcdir)/common.make
