#!/bin/bash

source ../GetSrcFromGithub.bash

#Usage: GetSrcFromGithub user package tag [sha512]

GetSrcFromGithub quiet libfec 1.0\
 b919904179ae0fd6fa2e56adb878eba9c\
d9db124828348c30c321921fa88884af4b\
012f6488f49cbd01330e3d33c0c9da7f7a\
ce7ce77a755dc147728f65dd0fd


# We created a patch with a diff from two directories
# and you want src to be the same as A
# diff -ur src A > patch.diff

cd src
patch -p1 < ../patch.diff
