# This is a GNU make file that uses GNU make make extensions


INSTALL_DIR = $(PREFIX)/include

#TODO: This will not build from a build directory that is
# not the same as the source directory.
INSTALLED_SRC := $(wildcard *.hpp)

include ../../../quickbuild.make
