# This is a GNU make file that uses GNU make make extensions


CXXFLAGS := -std=c++11 -g -Wall -Werror
CPPFLAGS := $(CXXFLAGS) -I../../include -I../../../liquid-dsp/src -DDEBUG

INSTALL_DIR = $(PREFIX)/plugins/ScenarioController


SC_Performance_Sweep_Utility.so_SOURCES := SC_Performance_Sweep_Utility.cpp


include ../../../../quickbuild.make
