# This is a GNU make file that uses GNU make make extensions


INSTALL_DIR = $(PREFIX)/plugins/ScenarioController/SC_Performance_Sweep_Utility

INSTALLED := $(wildcard *.cfg)

include ../../../../../quickbuild.make
