# This is a GNU make file that uses GNU make make extensions

top_srcdir := ../..

# There to install selected files in this directory
INSTALL_DIR = $(PREFIX)/public/lib

include $(top_srcdir)/common.make
